FROM --platform=$BUILDPLATFORM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04 AS base-env

SHELL ["/usr/bin/bash", "-c"]

# apt update
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -fs /usr/share/zoneinfo/Asia/Taipei /etc/localtime
COPY data/sources.list.arm64 /etc/apt/sources.list
RUN apt update -y
RUN apt upgrade -y
RUN apt install -y software-properties-common
RUN apt install -y \
    git \
    dialog \
    sudo \
    tzdata \
    keyboard-configuration \
    build-essential \
    lld-10 \
    g++-7 \
    cmake \
    ninja-build \
    libvulkan1 \
    python \
    python-dev \
    python3-dev \
    python3-pip \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    sed \
    curl \
    unzip \
    autoconf \
    libtool \
    rsync \
    libxml2-dev \
    curl
RUN dpkg-reconfigure --frontend noninteractive tzdata

# install llvm
RUN bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
RUN apt install -y clang-10

# build UnrealEngine
COPY data/UnrealEngine_4.26 /root/UnrealEngine_4.26
WORKDIR /root/UnrealEngine_4.26
RUN ./Setup.sh
RUN ./GenerateProjectFiles.sh
RUN make

FROM base-env AS carla-simulator

# # Install dev tools
# RUN apt install -y nano
# RUN apt install -y vim
# RUN apt install -y screen
# RUN apt install -y tmux
# RUN apt install -y emacs-nox
